### ISSUE TITLE
Thoshiba T3100e: Keyboard does not works

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1022]
*Describe the bug**

I installed the Last commit of 86box. The keyboard does not work. The XT based T1000/T1200 Works. I Also tested another 286/386 machines and works right in this respect.
This bug did not exist in older versions of 86box. And works correctly on PCem.

**To Reproduce**
1. Simply Mount the Hard Disk Image 86box
2. Configure The memory/Floppy disk options in the Setup Program

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 1909
 - 86Box version: Latest commit
 - Build type: regular

**Additional context**
Additional Glitch on both 86box/PCem : The memory assignment of XMS/EMS memory does not work when the Setup BIOS is accessed at the machine startup, but works correctly when invoked with the TEST3.EXE utility.
Here Is the hard disk image file.
(The TEST3.EXE utility is in C:\utils folder)

[Toshiba T1000 Hard Disk.zip](https://github.com/86Box/86Box/files/5338329/Toshiba.T1000.Hard.Disk.zip)

**Comment by OBattler** [comment]
I am in the process of completely rewriting the AT+ keyboard controller (almost done) and keyboard (have yet to start). Once that is done, this should be fixed.

**Comment by daviunic** [comment]
The keyboard seems to work fine now in build 2689, however the memory problems still persist.

If configured memory in Settings is >= 1536 KB, the system will report only a bad memory size CMOS error and report between 0.5MB and 1MB less than configured memory size (depending on EMS/XMS config you chose).

If configured memory in Settings is < 1536 KB, the system will report a memory verify error instead of counting the memory, then the CMOS error, and reported size in setup will be over 64MB.

**Comment by daviunic** [comment]
This machine works fine in PCem v16.

**Comment by OBattler** [comment]
> If configured memory in Settings is < 1536 KB, the system will report a memory verify error instead of counting the memory, then the CMOS error, and reported size in setup will be over 64MB.

That's just if you press the left arrow key, and must be a bug in CMOS Setup, since as of right now, 86Box's code is functionally identical to VARCem's, and this still happens.

**Comment by OBattler** [comment]
I just tested this in PCem v17, it happens there as well. As such, it's either a bug in the emulation of this, inherited from PCem (and not fixable unless someone finds an actual datasheet of this machine's chipset), or a bug in the BIOS. Aside from this, it all seems to work fine now (I no longer get that memory verify error). As such, I'm closing this.
