### ISSUE TITLE
WinNT4/2k causes segfault on reboot

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#1335]
**Describe the bug**
Windows NT4 and 2000 both cause 86Box to segfault when rebooting.

**To Reproduce**
Boot OS normally and then reboot, or boot from setup floppy/CD, quit and reboot

**Expected behavior**
Machine should reboot properly.

**Screenshots**
<img width="455" alt="msys_1" src="https://user-images.githubusercontent.com/29031916/112664733-4000d600-8e95-11eb-9592-66fea4e11c67.PNG">

**Desktop (please complete the following information):**
 - OS: Win10 20H2 19042.867
 - 86Box version: bd792b8e7a6e3c262204c6de8c9777f115a66b77
 - Build type: custom dev optimized

**Additional context**
~~Tested with Biostar MB-8600TTC and ECS P6BAP, seems to only happen on Pentium Pro and later CPUs~~
EDIT: Tested on NT4 with MSI MS-5146, bug seems to affect all boards that NT can run on

**Comment by OBattler** [comment]
Try now, I fixed a segmentation fault in mem_invalidate_range(), maybe it fixed this.

**Comment by dgurney** [comment]
Can confirm that rebooting NT works correctly for me now.

**Comment by WinFutureX** [comment]
Rebooting is still broken for me.
<img width="960" alt="86box_4" src="https://user-images.githubusercontent.com/29031916/113410969-36bcbf80-93e7-11eb-93d0-a9f77f284289.PNG">
I tried it on another board with a VIA Cyrix 3 without the dynamic recompiler and it works fine, so it's most probably a dynarec issue. The host CPU is a Core i7-1165G7, if that's relevant.

**Comment by dgurney** [comment]
Turns out I inadvertantly downloaded a dev build instead of a regular one for my "confirmation", and old dynarec indeed still crashes on reboot. Going back a few revisions it seems like this bug only happens with the old dynarec, as older official dev builds which use the new dynarec are also fine.

Can you try adding NEW_DYNAREC=y to your make command and see if the crash still occurs?

**Comment by WinFutureX** [comment]
Alright, rebuilt with new dynarec turned on, doesn't crash here.

**Comment by OBattler** [comment]
Try with old dynarec again on the build that is now compiling, see if it still crashes.

**Comment by WinFutureX** [comment]
Updated to latest commit, old dynarec still crashes:
<img width="960" alt="86box_5" src="https://user-images.githubusercontent.com/29031916/113502724-b28e4780-9560-11eb-9815-2cef4d893a27.PNG">

**Comment by WinFutureX** [comment]
This GDB output might be of use:
```
Thread 24 hit Breakpoint 1, resetx86 () at cpu/808x.c:1020
1020    {
(gdb) n
1021        reset_common(1);
(gdb)
1023        soft_reset_mask = 0;
(gdb)
1024    }
(gdb)
write_output (dev=0x17090930, val=222 '▒') at device/keyboard_at.c:1063
1063                    cpu_set_edx();
(gdb)
1067        dev->output_port = val;
(gdb)
1068    }
(gdb)
pulse_output (dev=0x17090930, mask=14 '\016') at device/keyboard_at.c:1115
1115            timer_set_delay_u64(&dev->pulse_cb, 6ULL * TIMER_USEC);
(gdb)
1117    }
(gdb)
write64_generic (priv=0x17090930, val=254 '▒') at device/keyboard_at.c:1248
1248                    return 0;
(gdb)
1253    }
(gdb)
write64_ami (priv=0x17090930, val=254 '▒') at device/keyboard_at.c:1462
1462    }
(gdb)
kbd_write (port=100, val=254 '▒', priv=0x17090930)
    at device/keyboard_at.c:2083
2083                                            bad = dev->write64_ven(dev, val);
(gdb)
2089                    if (dev->want60)
(gdb)
2091                    break;
(gdb)
2093    }
(gdb)
outb (port=100, val=254 '▒') at io.c:330
330                     found |= 1;
(gdb)
331                     qfound++;
(gdb)
333             p = q;
(gdb)
326         while(p) {
(gdb)
336         if (!found) {
(gdb)
347     }
(gdb)
opOUT_AL_DX (rmdat=2242) at cpu/x86_ops_io.h:120
120             if (nmi && nmi_enable && nmi_mask)
(gdb)
122             return x86_was_reset;
(gdb)
123     }
(gdb)
0x0827786a in ?? ()
(gdb)
Cannot find bounds of current function
(gdb)
Cannot find bounds of current function
(gdb)
Cannot find bounds of current function
(gdb)
Cannot find bounds of current function
(gdb)
Cannot find bounds of current function
(gdb) bt
#0  0x0827786a in ?? ()
#1  0x338eff99 in ?? ()
#2  0x00f85800 in gap3_sizes ()
#3  0x00786500 in ?? ()
#4  0x004000f8 in ?? ()
#5  0x00000000 in ?? ()
(gdb) c
Continuing.

Thread 24 received signal SIGSEGV, Segmentation fault.
0x0827786a in ?? ()
(gdb) bt
#0  0x0827786a in ?? ()
#1  0x338eff99 in ?? ()
#2  0x00f85800 in gap3_sizes ()
#3  0x00786500 in ?? ()
#4  0x004000f8 in ?? ()
#5  0x00000000 in ?? ()

```

**Comment by OBattler** [comment]
This is now fixed.
