### ISSUE TITLE
screen garbage after quitting games on newer 86box builds

### ISSUE THREAD

**Issue by honx4amiga** [86Box/86Box#1658]
using newer versions of 86box there is a not readable screen after quitting duke nukem 3d atomic edition version 1.5; i have to switch to 25 column mode to be able to read again. i can't exactly tell which build of 86box this behaviour started because i skipped directly from build 2980 to build 3142. this issue does not occur in build 2980. but it occurs in 3142 and also in latest 3156.

my configuration is:
machine type i486 (socket 2 and 3), machine [sis486] rise computer r418, display [pci] s3 vision964 (diamond stealth64 vram), emulated operating system is ms dos 6.22
86box 3.0 build 3156, host os: windows 7 ultimate

if i switch back to build 2980 again, this bug is gone again.

see screenshot:
![20210904-204551-909](https://user-images.githubusercontent.com/82286022/132107776-181a58a0-793d-498b-b8ab-5642afcbe2a7.png)

**Comment by honx4amiga** [comment]
i did some "backtracking". this issue starts exactly at build 3017: https://ci.86box.net/job/86Box/3017/
this bug does NOT occure at build 3016 and earlier.

**Comment by TC1995** [comment]
hmm, let me see if this is also related to the accel as well because, on that build, I disabled doubleword access.

**Comment by honx4amiga** [comment]
something similar happens if i use a dos based picture viewer called lxpic, see screenshot:
![20210904-215927-989](https://user-images.githubusercontent.com/82286022/132109107-ba0223a4-85df-4b72-b444-f0ac9edaea94.png)

that picture viewer i'm talking about (lxpic.zip) can be downloaded here: http://web.archive.org/web/20061111022251/http://www.buerg.com/download.htm

**Comment by TC1995** [comment]
yeah, I noticed, now let me test it.

**Comment by OBattler** [comment]
Closing this now because it has been fixed.

**Comment by honx4amiga** [comment]
is that build not available yet which is supposed it? because i just downloaded latest build 3160 (https://ci.86box.net/job/86Box/3160/) but this bug is still there. :(
in 3160 still screen garbage after quitting duke3d or trying to run lxpic.

**Comment by TC1995** [comment]
weird, let me check.

**Comment by TC1995** [comment]
dang, let me provide another approach for this.

**Comment by honx4amiga** [comment]
in build 3162 at least lxpic seems to be fixed. but duke3d now shows other issues, see screenshots:

![20210905-190235-314](https://user-images.githubusercontent.com/82286022/132138511-47fae2ec-9654-4bf1-85c0-8efaab57ee15.png)
![20210905-190236-419](https://user-images.githubusercontent.com/82286022/132138512-99c171ba-8401-47fe-901b-8d910f396ab6.png)
![20210905-190238-267](https://user-images.githubusercontent.com/82286022/132138513-165700fd-7e07-4e22-96d5-8ab0f0deaba0.png)
![20210905-190241-563](https://user-images.githubusercontent.com/82286022/132138514-315d5500-ae07-4906-8acc-9db916c05ce4.png)

**Comment by TC1995** [comment]
ffs s3, let me fix this.

**Comment by Ompronce** [comment]
The taskbar icon colors on Windows 9x for an active window are inverted (seen on Diamond Stealth64 DRAM 1MB).
![20210905-222021-908](https://user-images.githubusercontent.com/88358700/132142873-35154608-2ebd-4589-ad52-9840956f2352.png)

![20210905-221909-366](https://user-images.githubusercontent.com/88358700/132142855-756db9ff-1cb7-409a-a2cd-5c95f56d4009.png)

**Comment by honx4amiga** [comment]
in build 3165 latest issue from 3162 is gone but both issues mentioned in my first comment are back. :(

**Comment by honx4amiga** [comment]
which means also my third comment: screen garbage after quitting duke3d is present in build 3165 and also screen garbage when running lxpic program.

**Comment by TC1995** [comment]
should be solved now.
