### ISSUE TITLE
PS/2 mouse not working in [8088] Xi8088

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#2045]
**Describe the bug**
PS/2 mouse does not work in [8088] Xi8088. On an 86Box machine [8088] Xi8088, a PS/2 mouse can be enabled and POST shows that it is connected and the CTMOUSE.EXE driver reports that a PS/2 mouse is present and the mouse cursor appears, but the PS/2 mouse does not work. At the same time, in the 86Box machine [8088] Xi8088, the Microsoft Serial Mouse works fine.

**Expected behavior**
PS/2 mouse should work fine in [8088] Xi8088.

**Screenshots**
![2022-02-04_140019](https://user-images.githubusercontent.com/58270614/152528422-de1edef4-bda9-4907-9d98-8bb8b0065448.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.2 x64 Build 3478
 - Build type: regular, old recompiler.

**Comment by OBattler** [comment]
Are you sure CuteMouse even actually supports the 808x? And there is, from what I remember, another problem with CuteMouse - it assumes that INT 33h already has a valid vector, so it chains to it, but on 808x machines, it often does not. I created a small driver that installs a valid vector, but I need to find it.

**Comment by OBattler** [comment]
OK, I just fixed a bug with the PIC's on the Xi8088 - see if the PS/2 mouse now works.

**Comment by maximus105** [comment]
No, PS/2 mouse still doesn't work in [8088] Xi8088. I also tried another MITSUMI PS/2 mouse driver. And the PS/2 mouse doesn't work with it either (the driver reports that the PS/2 mouse was not found).
![2022-02-11_120957](https://user-images.githubusercontent.com/58270614/153574253-b8fed62d-6884-4f29-8d30-5696d8b2f62d.png)

**Comment by maximus105** [comment]
This file messes something up in MS-DOS, after running it, no programs run at all.
![2022-02-14_185547](https://user-images.githubusercontent.com/58270614/153910336-c6236722-4f5c-4da4-9843-678a50d0701d.png)

**Comment by OBattler** [comment]
Yes, I later realized that file is for DOS earlier than 3.00, while you're running 6.2x.
