### ISSUE TITLE
wrong exception generated

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [86Box/86Box#2583]
**Describe the bug**
under certain conditions, 86Box generates a wrong exception - 0Eh ( page fault) instead of 0Dh.

I've again created a test case, but this time the flaw might be not so "academic", because there's a good chance that fixing the bug will make CodeView for DOS - which currently exits with 

"runtime error R6915 - DOSX16 : unhandled exception"

run ( no guarantee, though ).

**To Reproduce**
start the test case. It displays "exc 0Eh".

**Expected behavior**
the test case should display "exc 0Dh".

**Additional context**
the actual address that causes the exception points indeed to "uncommitted" memory - but it's also "out of the descriptor limits". And this second condition has higher priority, hence an exception 0D is to be generated.

[EXC0D.ZIP](https://github.com/86Box/86Box/files/9275447/EXC0D.ZIP)

**Comment by BumfuzzledGames** [comment]
I'm also having this issue when trying to run CodeView. I found references in old knowledge base articles that this can be caused by some AMI BIOS versions, but it occurs on every machine type and BIOS that I've tried.

**Comment by Baron-von-Riedesel** [comment]
Confirmed. bug is fixed.

Regretably, CodeView 4.10 still exits with an "unhandled exception" - investigating...

**Comment by likearome** [comment]
![image](https://github.com/86Box/86Box/assets/39750066/8aa01a10-0da8-4ea9-a357-76ea9d2dc6ae)

It seems like this issue still exists in version 4.1.

MS-DOS 6.22 fresh install
MS C/C++ 7.0 fresh install
run CodeView and meet Exception.

**Comment by likearome** [comment]
![image](https://github.com/86Box/86Box/assets/39750066/e3e3ed5c-1d61-49b0-9901-d1d1cf031997)

EXC0D produced the output “exc 0D occurred.”
