### ISSUE TITLE
Keyboard is broken on build 4496 onwards

### ISSUE THREAD

**Issue by jguillaumes** [86Box/86Box#3236]
**Describe the bug**

Some applications (Borland Pascal 7.0 IDE, Borland C 3.1 IDE, Semware Editor for instance) don't get keyboard input (they DO get mouse input). The VM just beeps several times when any key is pressed.

**To Reproduce**

1. Start a VM with MS-DOS 6.22 and one of the mentioned applications installed.
2. Run the application
3. Press any key

**Expected behavior**

The application should respond to the keypress as expected. 

**Screenshots**

Not really useful, since there is no visual clue of the problem.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.3, running on a MacBook Pro with M1 processor
 - 86Box version: 86Box v4.0 [build 4496] [aab8eb809] [arm64, new dynarec]
 - Build information: Ditto

**Additional context**

Build 4494 seems to work. Haven't tested 4493 since it is marked as wrong in Jenkins.

**Comment by MrData1975** [comment]
Also as a note, the Portuguese keyboard in dos also doesn't work, and maybe some more keyboards won't work too, but with mode 860 and keyb PO i get english keyboard, and if i revert to a previous version, it works displaying the proper charset.

**Comment by DDXofficial** [comment]
This is an interesting situation here, considering that user input issues were being actively worked on with promising results. I will be sure to pass this on to the dev team.

In the meantime, would you be able to share your 86Box configuration file (86Box.cfg) or a summary of which hardware you selected for the virtual machine? (i.e. machine name and type [286? 386? 486?], mouse choice, etc.)

**Comment by ArnoldUK** [comment]
I can confirm that this is not an issue in build 4311 either but starting turbo pascal dos ide from within windows does lock up the keyboard and mouse. Although, I expect this is a windows fault more than an emulator fault.

**Comment by OBattler** [comment]
The Turbo Pascal bug is fixed already.

**Comment by marco-sacchi** [comment]
First of all, keep working on the project, it's awesome!

I think this issue isn't resolved.

I'm running 86Box v5.0 [build 7600] [0b66fccf0] [x86_64, dynarec]

Emulated System:
- Olivetti M300, IBM PS/1 model 2121 -class machine
- CPU: 386sx 16MHz + 387 coprocessor
- standard VGA
- AT keyboard, PS/2 mouse
- 4MB RAM
- 40MB HDD
- DOS 5.0

Host System:
- Microsoft Windows 11 Pro - 10.0.26100 build 26100
- CPU: Intel(R) Core(TM) i7-14700KF, 3400 MHz, 20 cores
- 32GB RAM

Contrary to what was written above, it's not related to Windows (I think it refers to the one emulated inside the VM), but to the **DPMI interface in general** (which is used even from Windows, if I remember correctly).

Editors or IDEs that do not run in protected mode, such as DOS EDIT or BASIC, GWBASIC, QuickBasic 4.5, Turbo Pascal 7.0, do not present any problems.

Those that do run in protected mode, such as Turbo C++ 3.0, Borland C 3.0, SETEDIT, have correct mouse emulation, but not keyboard emulation, which presents the following problems:
- Some keystrokes are not detected
- The state of the SHIFT key, and perhaps other modifiers, sometimes changes state without being pressed, while typing other keys

I have run tests that have not been able to mitigate the problem:
- Changing the PIT mode and the CPU frame size
- Changing the keyboard from AT to PS/2
- Removing the mouse device and driver

I attach the machine configuration file, renamed to `86box.cfg.txt` to allow upload; you can ignore the secondary disk that I temporarily use as swap space with the host system.

[86box.cfg.txt](https://github.com/user-attachments/files/22581736/86box.cfg.txt)

**Comment by OBattler** [comment]
I have no idea why those programs misbehave, why it breaks specifically under DPMI.

If this is a regression, then I'd appreciate it if someone properly bisected it and found out when it was introduced.

**Comment by OBattler** [comment]
Edit: 4496 onwards... I have no idea which of the changes there caused this.

**Comment by marco-sacchi** [comment]
@OBattler I'm continuing to investigate, and from what I've been able to determine, it's not strictly due to 86Box's emulation, but perhaps to EMM386's poor handling of real-mode/protected-mode switches and its VCPI host implementation.

Removing EMM386 for testing resolved the issues.

I'll update you with further details that may be useful to other 86Box users in the future.

EDIT:

This may solve the problem for MS-DOS 6.0+, but unfortunately it's not available in version 5.0:

```
DEVICE=EMM386.EXE NOEMS NOVCPI
```

**Comment by OBattler** [comment]
This explains why I wasn't able to reproduce the issue just now - I wasn't using EMM386.

**Comment by OBattler** [comment]
This is strange - I can't reproduce it even with EMM386.

If the recompiler is on, it may be due to some sort of idler? I use POWER.EXE, maybe that mitigates it?

**Comment by OBattler** [comment]
Even with POWER.EXE removed, I can't reproduce it - DOSKEY maybe?

**Comment by OBattler** [comment]
Nope, still fine.. no idea what's going on then. I'm using IBM PC DOS 7.0 but Windows 9x's EMM386. NOEMS is set, perhaps that's why?

**Comment by marco-sacchi** [comment]
> If the recompiler is on

The recompiler option is disabled for the i386SX / [ISA] IBM PS/1 model 2121 machine.

> DOSKEY maybe

No, I removed DOSKEY for testing but it didn't fix the problem, it's definitely related to the EMM386 VCPI, or some time in the specific configuration I attached.

> I'm using IBM PC DOS 7.0 but Windows 9x's EMM386.

I was already using `DEVICE=EMM386.EXE NOEMS` 
It might be the version of EMM386 included in DOS 5.0, I'll check with a VM running MS-DOS 6.22.

**Comment by OBattler** [comment]
So either the Windows 9x version of EMM386 lacks VCPI entirely or it behaves differently.

**Comment by OBattler** [comment]
Which MS-DOS 5.00 are you using - the original or 5.00a? The original has EMM386 4.20, the latter 4.33, which fixed something important, but I forgot what now.

**Comment by OBattler** [comment]
And I forgot if IBM also updated their DOS 5.0 EMM386 and if so, in which version. But I suspect that in the case of IBM DOS 5.0, you may need 5.02.

**Comment by marco-sacchi** [comment]
> So either the Windows 9x version of EMM386 lacks VCPI entirely or it behaves differently.

I think newer versions of EMM386 have improved handling for applications that use VCPI/DPMI.

It's strange, though. I've never had any problems with Virtual PC VM, but it was running MS-DOS 6.22, and I may have been using a memory manager other than EMM386.

> Which MS-DOS 5.00 are you using - the original or 5.00a?

I'm using original MS-DOS 5.00, as reported by `ver` command. I rebuilt the hardware configuration of a real machine I had, using the same version of MS-DOS. But I think upgrading to 5.00a is absolutely fine.

Versions for DOS 5.00:
HIMEM: DOS XMS Driver, Version 2.77 - 02/27/91
EMM386: MICROSOFT Expanded Memory Manager 386  Version 4.20.06X

Versions for DOS 5.00a
HIMEM: DOS XMS Driver, Version 2.78 - 09/19/91
EMM386: MICROSOFT Expanded Memory Manager 386  Version 4.33.06X

Both don't work, I even tried excluding specific regions that can normally cause conflicts with `X=`, but without success.

> If the recompiler is on, it may be due to some sort of idler? I use POWER.EXE, maybe that mitigates it?

Sorry, I missed that earlier. No, I don't use any idlers, at least not yet.

If I find a solution or more information I will update you.

**Comment by OBattler** [comment]
Just a note - both will report 5.00 in VER.

And well, perhaps an idler would mitigate the problem, I don't know.

**Comment by marco-sacchi** [comment]
I've tried:

- MS-DOS 5.00a on a new 386DX machine with an `ASUS ISA-386C [SiS 310]` machine, with no luck
- MS-DOS 6.22 on the same 386DX machine, with `EMM386` and `QEMM386`. The latter performs much better, and I no longer have keyboard problems with Borland IDEs. However, `SETEDIT` and `RHIDE`, which use `CWSDPMI` as a DOS extender, continue to cause keyboard and mouse problems
- I also tried excluding the regions most likely to cause keyboard IRQ conflicts with QEMM, but they didn't make any difference.

I've tested previous versions of 86Box up to `4.0.1 build 5111`, but they all behave the same way.

I believe it's a timing issue with the specific combination of the EMM/QEMM memory manager with the CWSDPMI DPMI server.
Note, however, that this behavior isn't seen in virtualization programs like Virtual PC.

If you'd like to investigate, you can find the versions of `SETEDIT` and `RHIDE` I'm using here: https://mirror-hk.koddos.net/djgpp/deleted/v2apps/

Thanks for the hints anyway.

**Comment by marco-sacchi** [comment]
I've finally isolated the component causing the conflict, and I want to share the solution for those who have gone crazy like me.

`EMM386` and `QEMM386` (with `QDPMI`) both implement the DPMI 0.9 specification, which appears to be unstable, or perhaps not well supported by the 86Box. I was able to identify it by chance from a message I'd never seen before when launching the `WD` Watcom debugger, which stated that it was impossible to **debug a program with DOS extender on a DPMI 0.9 host**.

To resolve the issue, I removed the `QDPMI` loading from `config.sys`. I think that in the case of `EMM386`, it should be sufficient to add the `NOVCPI` parameter if available.

Now, binaries that embed their DPMI host will use that, while those that don't (like `SETEDIT`) will report it. In this case, simply make the DPMI 1.0 host available by copying, for example, cwsdpmi.exe to the same path as the editor, or by making it accessible via the `PATH` environment variable.

Finally, both the keyboard and mouse work perfectly in all the editors and IDEs I have.

---

> It's strange, though. I've never had any problems with Virtual PC VM, but it was running MS-DOS 6.22, and I may have been using a memory manager other than EMM386.

I checked the VM again and it wasn't loading `QDPMI`. I don't remember if I manually configured `QEMM386`, but in the 86box machine I used their `OPTIMIZE` binary to auto-configure drivers loading and free up as much conventional memory as possible.

> However, SETEDIT and RHIDE, which use CWSDPMI as a DOS extender, continue to cause keyboard and mouse problems.

I think that binaries compiled with djgpp give precedence to any DPMI host already available on the system, whether they have it embedded (like `RHIDE`) or not (like `SETEDIT`) and in my system they were using a 0.9 host instead of the one expected and included in djgpp which is 1.0 compliant.
