### ISSUE TITLE
Extreme Assault DOS game Voodoo transparency glitch

### ISSUE THREAD

**Issue by MX9000** [86Box/86Box#3304]
**Describe the bug**
Trying the 3dfx version of the game in 86Box I noticed that the shadow in the top left corner, the text boxes, the radar and the explosions have the transparency effects corrupted.
I found this thread on the subject : https://www.vogons.org/viewtopic.php?t=62853
I also tried the patches to update the game to 1.2.2 version but the glitch remains.

**To Reproduce**
1. Configure a Pentium machine with Voodoo Graphics (I used MS-DOS 6.22 as OS)
2. Launch the game with command 3dfx.bat
3. See the glitch during the first mission

**Expected behavior**
Transparencies should be displayed properly.

**Screenshots**

3dfx mode:
![Monitor_1_20230504-105153-297297](https://user-images.githubusercontent.com/58113425/236158111-e82a1a77-b8f5-4ec8-9734-b5257c314ab7.png)
![Monitor_1_20230504-105221-017017](https://user-images.githubusercontent.com/58113425/236158174-02c947da-1a5c-4acd-95f3-90a4675b4d8d.png)

Software mode:
![Monitor_1_20230504-105505-811811](https://user-images.githubusercontent.com/58113425/236158221-d09f5e10-511e-4b91-96cc-54b69d6ef785.png)
![Monitor_1_20230504-105529-607607](https://user-images.githubusercontent.com/58113425/236158286-4d8dbb3a-e651-4d9d-9c47-1fe02fb6de74.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 bit version 22H2
 - 86Box version: 3.11
 - Build information: 86Box-Windows-32-b4311.zip

**Comment by efflixi** [comment]
Please try build #4875 and make sure your 3dfx files are the latest for that game (not just patching the game, unless those patches apply newer 3dfx files too).

**Comment by OBattler** [comment]
Closing because it's a 64-bit recompiler glitch, which is already being tracked in #2923.

**Comment by katho3d** [comment]
> Closing because it's a 64-bit recompiler glitch, which is already being tracked in #2923.

Hello, please reopen because I tried with 32-bit version of 86box and the issue exists in this version too. And @MX9000 also using the 32 bit version, as you can see in the description. So this is definitely not related to the 64 bit version only.

**Comment by eddmanx** [comment]
Can confirm it's not 64-bit related. Happens on 32-bit builds too, with the Voodoo dynarec both enabled and disabled.

**Comment by OBattler** [comment]
Issue reopened.

**Comment by OBattler** [comment]
Please try on the latest build of 86Box.

**Comment by eddmanx** [comment]
Tested with build 5587. It's still bugged.

**Comment by OBattler** [comment]
Closing because it's being tracked in #4483 .

**Comment by OBattler** [comment]
This is now fixed.

**Comment by eddmanx** [comment]
It still doesn't look exactly correct.

86box, Voodoo 1:
![Monitor_1_20250108-192746-281](https://github.com/user-attachments/assets/bd27b755-3f43-4818-a0ee-302e5f162a25)

Real hardware, Voodoo Banshee:
https://www.youtube.com/watch?v=CI7ODEqPRfM
![extreme](https://github.com/user-attachments/assets/8ac7de37-1bea-48c6-ae5b-3c0433549b0b)

**Comment by eddmanx** [comment]
Apparently it used to be broken with glidos too.
https://www.youtube.com/watch?v=ueeZjuJQE3A

**Comment by eddmanx** [comment]
Regarding support for different Voodoo cards:

1. The retail game works with Voodoo 1.
2. Rush support was added with patch 1.2.
3. Voodoo 2 and up with patch 1.2.2.

The patches must be installed in order; they don't seem to be cumulative.

**Comment by Kappa971** [comment]
There's definitely still something wrong:

<img width="1440" height="1080" alt="Image" src="https://github.com/user-attachments/assets/6a876ad7-1e8b-4704-b7f1-304ae6662f58" />
<img width="1440" height="1080" alt="Image" src="https://github.com/user-attachments/assets/52fe4ca4-b972-48c2-937f-0f1c8fb8866b" />

**Comment by yes897** [comment]
can someone reopen this issue again if the above game is the same game in this issue?
