### ISSUE TITLE
Sound does not work under Windows 95

### ISSUE THREAD

**Issue by Xuser641** [86Box/86Box#3498]
**Describe the bug**
When playing a sound, instead of hearing the sound, you just hear static "clicks/pops".

**To Reproduce**
1. Create a new VM with win95 and a SoundBlaster 16. (Bug may also happen on other sound cards)
2. Try playing a any sound
3. Hear static "clicks/pops" but no sound

**Expected behavior**
Sounds should play.

**Desktop (please complete the following information):**
 - OS = Windows 10 x64
 - 86Box version 4.0 build 4739
 - x64

**Additional context**
The POST beep plays fine. I/O settings are the default and 95 reports no errors/conflicts.

I'll try and actually respond this time!

**Comment by OBattler** [comment]
Which dynarec, old or new?

**Comment by TC1995** [comment]
Also, port/irq/dma/mpu401?

**Comment by OBattler** [comment]
In fact, the entire 86box.cfg is required to help us diagnose the issue.

**Comment by Xuser641** [comment]
Old recompiler - and config attached
[86box.cfg.txt](https://github.com/86Box/86Box/files/12232110/86box.cfg.txt)

**Comment by OBattler** [comment]
The only thing it can possibly be is the IRQ being shared with the LPT port - try moving the Sound Blaster 16 to IRQ 7 and see if it works.

**Comment by Xuser641** [comment]
I have moved the soundblaster 16 to IRQ 7, and manually configured windows 95 to use IRQ 7, same problem.
Also interestingly device manager reports that the system device "PCI bus" has been disabled in the hardware. Don't know if that is related though.

**Comment by OBattler** [comment]
Update to the latest 86Box build. Turns out this is the third known case of problems on the 430nx (and yes, I presume that could break ISA sound as well since ISA goes through PCI on these chipsets) that were fixed with the PCI write.

**Comment by Xuser641** [comment]
I have updated to the latest build and am still having the same problem.
