### ISSUE TITLE
RTL8139 does not appear to connect properly under Windows 7

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#3834]
### What happened?

In Windows 7, the RTL8139 network adapter always appears as disconnected, even if the "connected" option is selected:
![Screenshot_20231119_232845](https://github.com/86Box/86Box/assets/29031916/4cafdec8-d108-4b29-9fb1-95637f4d407f)

### Configuration file

```ini
[General]
vid_renderer = qt_opengl
rctrl_is_lalt = 1
confirm_exit = 0
hide_status_bar = 1
hide_tool_bar = 1

[Machine]
machine = vpc2007
cpu_family = celeron_mendocino
cpu_speed = 300000000
cpu_multi = 4.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
cpu_manufacturer = 1
cpu = 4
mem_size = 524288

[Video]
gfxcard = mystique_220

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = cmi8738

[Storage controllers]
hdc = internal

[C-Media CMI8738]
six_channel = 1
receive_input = 1

[Realtek RTL8139C+ #1]
mac = 0c:20:ae

[Network]
net_01_card = rtl8139c+
net_01_net_type = slirp

[Hard disks]
hdd_01_parameters = 63, 16, 33288, 0, ide
hdd_01_fn = win7.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_turbo = 1
fdd_01_check_bpb = 0
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
fdd_02_type = none
cdrom_01_type = 86BOX_CD-ROM_1.00
```

### Operating system

Fedora 38

### CPU

Intel Core i7-1165G7

### 86Box version

f8902572372314fd1489996918b38d8bde9abb48

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [X] Debug build

### Download source

I built 86Box myself (please tell us more about your build configuration)

### Additional context

My build script:
```bash
rm -r out/
cmake -S . -B out -DDEV_BRANCH=y -DCMAKE_C_FLAGS="-g -Og -march=native" -DCMAKE_CXX_FLAGS="-g -Og -march=native"
cd out
make -j8 && cp src/86Box ..
```

**Comment by MatthewH12** [comment]
I tried using the 8139C under Windows 2000, and it detected and showed connection, but wouldn't ping local network. Upon further inspection, the card had NO network address set. It showed as 00-00-00-00-00-00. Switching to the 8029(AS), works fine and shows a proper network address of 00-E0-4C-F7-4A-05.

86Box v4.1 Build 5226 - ac63ea661, i386, old dynarec.

**Comment by OBattler** [comment]
Can both of you upload your VM's please?

**Comment by OBattler** [comment]
Fixed the MAC address in Windows 2000 - the card now seems to properly work there.

**Comment by OBattler** [comment]
@WinFutureX See if the problem still persists on the latest build of 86Box.

**Comment by WinFutureX** [comment]
The problem is still here.
![Monitor_1_20231220-041830-946](https://github.com/86Box/86Box/assets/29031916/37d4955f-4f07-4c72-8de4-976e348463ec)
[Here's the VM.](https://mega.nz/file/T9wQmBzQ#MXDJRCOkVKB6Sgg2-TTHfV26HlyRQhJN6f5A9FrqLJg) (warning: disk is 16GB!)

**Comment by OBattler** [comment]
I need the NVR folder as well.

**Comment by WinFutureX** [comment]
[Here.](https://github.com/86Box/86Box/files/13720520/nvr.zip)

**Comment by OBattler** [comment]
This is going to be a CANTFIX - I now even have the EEPROM improved on my end and still the same problem - Windows 7 gets a bogus MAC address and no connectivity, it doesn't even try accessing any register other than the EEPROM register.

**Comment by sskras** [comment]
> I now even have the EEPROM improved on my end and still the same problem

That's interesting. @OBattler, any guesses why?

**Comment by OBattler** [comment]
I have absolutely no idea.
