### ISSUE TITLE
IBM XGA demo program is broken on XGA adapter

### ISSUE THREAD

**Issue by WNT50** [86Box/86Box#5771]
### Checklist

- [x] I **have searched** the issue tracker and **was unable** to find an [open](../issues?q=is%3Aissue+is%3Aopen) or [closed](../issues?q=is%3Aissue+is%3Aclosed) issue matching what I'm seeing.
- [x] I **have verified** that the issue is happening in the **[latest nightly build](https://ci.86box.net/job/86Box/lastSuccessfulBuild/artifact/)**, or the latest commit, if building from source.

### What happened?

IBM XGA demo program from [XGA v2.12 driver disk](https://www.ardent-tool.com/video/XGA_Files.html#XGA212) (in `XGAPCDOS` folder) displays wrong color and doesn't response to keyboard input any longer after running. The right color should like [this](https://github.com/86Box/86Box/issues/2968#issuecomment-1353431471) (they both use the Adapter Interface).

<img width="1024" height="768" alt="Image" src="https://github.com/user-attachments/assets/831b0b9b-8ed4-484c-9672-5d1ba341f35c" />

### Configuration file

```ini
[INMOS XGA (ISA)]
type = 1
instance = 6
ext_mem_addr = 00F0
dma = 7

[Microsoft Serial Mouse]
port = 0
buttons = 2

[General]
force_43 = 1
host_cpu = AMD Ryzen 7 5800H with Radeon Graphics         
uuid = 7a1ee9b7-dab1-5630-86d3-26a5c42edc3f
vid_renderer = qt_software

[Machine]
cpu_family = i386dx
cpu_multi = 1
cpu_speed = 40000000
cpu_use_dynarec = 0
machine = acc386
mem_size = 8192

[Video]
gfxcard = inmos_xga_isa

[Input devices]
mouse_type = msserial

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = dot_matrix

[Storage controllers]
hdc = st506_at

[Hard disks]
hdd_01_fn = disk.img
hdd_01_mfm_channel = 0
hdd_01_parameters = 17, 7, 855, 0, mfm

[Floppy and CD-ROM drives]
fdd_01_turbo = 1
fdd_01_type = 35_2hd
fdd_02_turbo = 1
fdd_02_type = 525_2hd
```

### Operating system

Windows 11 24H2

### 86Box version

v5.0 build 7221

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Additional context

[XGA2ISA.zip](https://github.com/user-attachments/files/21152791/XGA2ISA.zip)

**Comment by jriwanek** [comment]
Does this work on the actual IBM XGA adaptor (MCA)? I notice you're running it on the Inmos (ISA)

**Comment by WNT50** [comment]
IBM MCA XGA adapter still produces the wrong display (I tested both XGA-1 and XGA-2).

<img width="1024" height="768" alt="Image" src="https://github.com/user-attachments/assets/82def759-293a-420e-9ba5-fda11f9ff417" />

**Comment by TC1995** [comment]
By actual, we mean real hardware.

**Comment by WNT50** [comment]
@TC1995 I found this demo running on PS/2 55sx with XGA-1 adapter on [vogons](https://www.vogons.org/viewtopic.php?f=46&t=96933). The demo should run like this picture.

![Image](https://github.com/user-attachments/assets/57adfa66-55f4-439c-b73d-38c1dd151f33)

**Comment by TC1995** [comment]
Ok, the palette colors are fixed, but in that screenshot above, is it using the XGA fonts or 8514/A fonts? (in the installation of the xga 2.12 disk for DOS).
Edit: here at the installation program before the demo starts.

<img width="720" height="400" alt="Image" src="https://github.com/user-attachments/assets/d7a838f5-95e2-4a01-83e6-45bf7b51ba53" />

**Comment by WNT50** [comment]
@TC1995 I use the XGA Adapter font set (press Y).

**Comment by WNT50** [comment]
I tested both XGA and 8514/A Adapter font set with results attached. While XGA font set still do not work, 8514/A font set works better but still with some glitches.

XGA Adapter font set:
<img width="2048" height="1536" alt="Image" src="https://github.com/user-attachments/assets/b4260c49-8e8b-446e-8d67-eeea9359c0c0" />

8514/A Adapter font set:
<img width="2048" height="1536" alt="Image" src="https://github.com/user-attachments/assets/510037b9-4a69-418e-b973-cc20001014ae" />

**Comment by OBattler** [comment]
Oops, this is the issue I should have mentioned in the commit, the XGA font set is now fixed.

<img width="1026" height="864" alt="Image" src="https://github.com/user-attachments/assets/367f1de1-e5f2-486e-97a3-e2d963986aae" />
